BEGIN;

DROP POLICY IF EXISTS tenant_isolation ON billing.payments;
ALTER TABLE billing.payments NO FORCE ROW LEVEL SECURITY;
ALTER TABLE billing.payments DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON billing.subscriptions;
ALTER TABLE billing.subscriptions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE billing.subscriptions DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON billing.wallets;
ALTER TABLE billing.wallets NO FORCE ROW LEVEL SECURITY;
ALTER TABLE billing.wallets DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON catalog.saving_products;
ALTER TABLE catalog.saving_products NO FORCE ROW LEVEL SECURITY;
ALTER TABLE catalog.saving_products DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON commerce.carts;
ALTER TABLE commerce.carts NO FORCE ROW LEVEL SECURITY;
ALTER TABLE commerce.carts DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON promo.ads;
ALTER TABLE promo.ads NO FORCE ROW LEVEL SECURITY;
ALTER TABLE promo.ads DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON promo.offer_clicks;
ALTER TABLE promo.offer_clicks NO FORCE ROW LEVEL SECURITY;
ALTER TABLE promo.offer_clicks DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON promo.offer_views;
ALTER TABLE promo.offer_views NO FORCE ROW LEVEL SECURITY;
ALTER TABLE promo.offer_views DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON workflow.purchase_priority_engines;
ALTER TABLE workflow.purchase_priority_engines NO FORCE ROW LEVEL SECURITY;
ALTER TABLE workflow.purchase_priority_engines DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON workflow.report_issues;
ALTER TABLE workflow.report_issues NO FORCE ROW LEVEL SECURITY;
ALTER TABLE workflow.report_issues DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON commerce.cart_items;
ALTER TABLE commerce.cart_items NO FORCE ROW LEVEL SECURITY;
ALTER TABLE commerce.cart_items DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON commerce.order_status_history;
ALTER TABLE commerce.order_status_history NO FORCE ROW LEVEL SECURITY;
ALTER TABLE commerce.order_status_history DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON billing.wallet_transactions;
ALTER TABLE billing.wallet_transactions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE billing.wallet_transactions DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON billing.invoice_lines;
ALTER TABLE billing.invoice_lines NO FORCE ROW LEVEL SECURITY;
ALTER TABLE billing.invoice_lines DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON promo.offer_products;
ALTER TABLE promo.offer_products NO FORCE ROW LEVEL SECURITY;
ALTER TABLE promo.offer_products DISABLE ROW LEVEL SECURITY;

COMMIT;
