ALTER TABLE billing.invoices ALTER COLUMN notes DROP NOT NULL;
ALTER TABLE billing.invoices ALTER COLUMN notes DROP DEFAULT;
ALTER TABLE billing.wallet_transactions ALTER COLUMN reference_type DROP NOT NULL;
ALTER TABLE billing.wallet_transactions ALTER COLUMN reference_type DROP DEFAULT;
ALTER TABLE billing.wallet_transactions ALTER COLUMN description DROP NOT NULL;
ALTER TABLE billing.wallet_transactions ALTER COLUMN description DROP DEFAULT;
ALTER TABLE billing.payments ALTER COLUMN transaction_id DROP NOT NULL;
ALTER TABLE billing.payments ALTER COLUMN transaction_id DROP DEFAULT;
ALTER TABLE billing.payments ALTER COLUMN reference_number DROP NOT NULL;
ALTER TABLE billing.payments ALTER COLUMN reference_number DROP DEFAULT;
ALTER TABLE catalog.products ALTER COLUMN sku DROP NOT NULL;
ALTER TABLE catalog.products ALTER COLUMN sku DROP DEFAULT;
ALTER TABLE catalog.products ALTER COLUMN barcode DROP NOT NULL;
ALTER TABLE catalog.products ALTER COLUMN barcode DROP DEFAULT;
ALTER TABLE catalog.products ALTER COLUMN image DROP NOT NULL;
ALTER TABLE catalog.products ALTER COLUMN image DROP DEFAULT;
ALTER TABLE catalog.products ALTER COLUMN image_link DROP NOT NULL;
ALTER TABLE catalog.products ALTER COLUMN image_link DROP DEFAULT;
ALTER TABLE catalog.products ALTER COLUMN dosage_form DROP NOT NULL;
ALTER TABLE catalog.products ALTER COLUMN dosage_form DROP DEFAULT;
ALTER TABLE catalog.products ALTER COLUMN scientific_name DROP NOT NULL;
ALTER TABLE catalog.products ALTER COLUMN scientific_name DROP DEFAULT;
ALTER TABLE catalog.products ALTER COLUMN pharmacology DROP NOT NULL;
ALTER TABLE catalog.products ALTER COLUMN pharmacology DROP DEFAULT;
ALTER TABLE catalog.products ALTER COLUMN active DROP NOT NULL;
ALTER TABLE catalog.products ALTER COLUMN active DROP DEFAULT;
ALTER TABLE catalog.products ALTER COLUMN concentration DROP NOT NULL;
ALTER TABLE catalog.products ALTER COLUMN concentration DROP DEFAULT;
ALTER TABLE catalog.products ALTER COLUMN unit DROP NOT NULL;
ALTER TABLE catalog.products ALTER COLUMN unit DROP DEFAULT;
ALTER TABLE catalog.products ALTER COLUMN manufacturing_companies DROP NOT NULL;
ALTER TABLE catalog.products ALTER COLUMN manufacturing_companies DROP DEFAULT;
ALTER TABLE catalog.categories ALTER COLUMN icon DROP NOT NULL;
ALTER TABLE catalog.categories ALTER COLUMN icon DROP DEFAULT;
ALTER TABLE catalog.categories ALTER COLUMN image DROP NOT NULL;
ALTER TABLE catalog.categories ALTER COLUMN image DROP DEFAULT;
ALTER TABLE catalog.brands ALTER COLUMN image DROP NOT NULL;
ALTER TABLE catalog.brands ALTER COLUMN image DROP DEFAULT;
ALTER TABLE catalog.product_variants ALTER COLUMN sku DROP NOT NULL;
ALTER TABLE catalog.product_variants ALTER COLUMN sku DROP DEFAULT;
ALTER TABLE catalog.product_variants ALTER COLUMN barcode DROP NOT NULL;
ALTER TABLE catalog.product_variants ALTER COLUMN barcode DROP DEFAULT;
ALTER TABLE catalog.product_variants ALTER COLUMN unit DROP NOT NULL;
ALTER TABLE catalog.product_variants ALTER COLUMN unit DROP DEFAULT;
ALTER TABLE catalog.product_variants ALTER COLUMN image DROP NOT NULL;
ALTER TABLE catalog.product_variants ALTER COLUMN image DROP DEFAULT;
ALTER TABLE commerce.order_shipments ALTER COLUMN tracking_number DROP NOT NULL;
ALTER TABLE commerce.order_shipments ALTER COLUMN tracking_number DROP DEFAULT;
ALTER TABLE commerce.order_shipments ALTER COLUMN carrier_name DROP NOT NULL;
ALTER TABLE commerce.order_shipments ALTER COLUMN carrier_name DROP DEFAULT;
ALTER TABLE commerce.order_status_history ALTER COLUMN notes DROP NOT NULL;
ALTER TABLE commerce.order_status_history ALTER COLUMN notes DROP DEFAULT;
ALTER TABLE commerce.orders ALTER COLUMN notes DROP NOT NULL;
ALTER TABLE commerce.orders ALTER COLUMN notes DROP DEFAULT;
ALTER TABLE commerce.quote_requests ALTER COLUMN buyer_notes DROP NOT NULL;
ALTER TABLE commerce.quote_requests ALTER COLUMN buyer_notes DROP DEFAULT;
ALTER TABLE commerce.quote_requests ALTER COLUMN supplier_notes DROP NOT NULL;
ALTER TABLE commerce.quote_requests ALTER COLUMN supplier_notes DROP DEFAULT;
ALTER TABLE identity.user_addresses ALTER COLUMN phone DROP NOT NULL;
ALTER TABLE identity.user_addresses ALTER COLUMN phone DROP DEFAULT;
ALTER TABLE identity.user_addresses ALTER COLUMN building DROP NOT NULL;
ALTER TABLE identity.user_addresses ALTER COLUMN building DROP DEFAULT;
ALTER TABLE identity.user_addresses ALTER COLUMN floor DROP NOT NULL;
ALTER TABLE identity.user_addresses ALTER COLUMN floor DROP DEFAULT;
ALTER TABLE identity.user_addresses ALTER COLUMN apartment DROP NOT NULL;
ALTER TABLE identity.user_addresses ALTER COLUMN apartment DROP DEFAULT;
ALTER TABLE identity.users ALTER COLUMN phone DROP NOT NULL;
ALTER TABLE identity.users ALTER COLUMN phone DROP DEFAULT;
ALTER TABLE identity.user_security ALTER COLUMN last_user_agent DROP NOT NULL;
ALTER TABLE identity.user_security ALTER COLUMN last_user_agent DROP DEFAULT;
ALTER TABLE ingest.import_sessions ALTER COLUMN error_message DROP NOT NULL;
ALTER TABLE ingest.import_sessions ALTER COLUMN error_message DROP DEFAULT;
ALTER TABLE ingest.import_rows ALTER COLUMN normalized_name DROP NOT NULL;
ALTER TABLE ingest.import_rows ALTER COLUMN normalized_name DROP DEFAULT;
ALTER TABLE inventory.stock_movements ALTER COLUMN details DROP NOT NULL;
ALTER TABLE inventory.stock_movements ALTER COLUMN details DROP DEFAULT;
ALTER TABLE inventory.stock_movements ALTER COLUMN reference_type DROP NOT NULL;
ALTER TABLE inventory.stock_movements ALTER COLUMN reference_type DROP DEFAULT;
ALTER TABLE inventory.warehouse_transfers ALTER COLUMN notes DROP NOT NULL;
ALTER TABLE inventory.warehouse_transfers ALTER COLUMN notes DROP DEFAULT;
ALTER TABLE inventory.warehouses ALTER COLUMN code DROP NOT NULL;
ALTER TABLE inventory.warehouses ALTER COLUMN code DROP DEFAULT;
ALTER TABLE inventory.warehouses ALTER COLUMN address DROP NOT NULL;
ALTER TABLE inventory.warehouses ALTER COLUMN address DROP DEFAULT;
ALTER TABLE inventory.warehouses ALTER COLUMN phone DROP NOT NULL;
ALTER TABLE inventory.warehouses ALTER COLUMN phone DROP DEFAULT;
ALTER TABLE notifications.logs ALTER COLUMN error_message DROP NOT NULL;
ALTER TABLE notifications.logs ALTER COLUMN error_message DROP DEFAULT;
ALTER TABLE org.organization_reviews ALTER COLUMN review_text DROP NOT NULL;
ALTER TABLE org.organization_reviews ALTER COLUMN review_text DROP DEFAULT;
ALTER TABLE platform_admin.system_settings ALTER COLUMN description DROP NOT NULL;
ALTER TABLE platform_admin.system_settings ALTER COLUMN description DROP DEFAULT;
ALTER TABLE platform_admin.contact_messages ALTER COLUMN phone DROP NOT NULL;
ALTER TABLE platform_admin.contact_messages ALTER COLUMN phone DROP DEFAULT;
ALTER TABLE workflow.weekly_coverages ALTER COLUMN address DROP NOT NULL;
ALTER TABLE workflow.weekly_coverages ALTER COLUMN address DROP DEFAULT;
ALTER TABLE workflow.report_issues ALTER COLUMN response_notes DROP NOT NULL;
ALTER TABLE workflow.report_issues ALTER COLUMN response_notes DROP DEFAULT;
