BEGIN;
ALTER TABLE platform_admin.contact_messages
  ADD COLUMN IF NOT EXISTS ip TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS user_agent TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS user_id BIGINT REFERENCES identity.users(id) ON DELETE SET NULL;
COMMIT;
