-- 206_seed_notification_templates.up.sql
--
-- Seed notifications.templates with all platform notification event definitions (WO-35).
-- Populates the table so operators can inspect, localize, and edit notification wording,
-- resolving the empty-table defect.

BEGIN;

INSERT INTO notifications.templates (slug, channel, title, body, is_active)
VALUES
    -- Commerce & Orders
    ('order.placed', 'in_app',
     '{"ar": "تم استلام طلبك {order_number}", "en": "Order Received {order_number}"}'::jsonb,
     '{"ar": "تم تسجيل طلبك بنجاح بإجمالي {total_amount} ج.م وجارٍ مراجعته من قبل المورد.", "en": "Your order has been recorded with total {total_amount} EGP and is being reviewed."}'::jsonb,
     true),
    ('order.status_changed', 'in_app',
     '{"ar": "تحديث حالة الطلب {order_number}", "en": "Order Status Update {order_number}"}'::jsonb,
     '{"ar": "قام المورد {vendor_name} بتحديث حالة طلبك إلى: {status}. {reason}", "en": "Supplier {vendor_name} updated order status to: {status}. {reason}"}'::jsonb,
     true),
    ('order.cancelled_by_buyer', 'in_app',
     '{"ar": "إلغاء الطلب من قبل المشتري {order_number}", "en": "Order Cancelled by Buyer {order_number}"}'::jsonb,
     '{"ar": "قام المشتري {customer_name} بإلغاء الطلب {order_number}. السبب: {reason}", "en": "Buyer {customer_name} cancelled order {order_number}. Reason: {reason}"}'::jsonb,
     true),

    -- Purchase Requests & RFQs
    ('purchase_request.created', 'in_app',
     '{"ar": "طلب تسعير جديد #{request_id}", "en": "New RFQ #{request_id}"}'::jsonb,
     '{"ar": "أرسلت صيدلية {pharmacy_name} طلب تسعير لـ {item_count} أصناف.", "en": "Pharmacy {pharmacy_name} submitted an RFQ with {item_count} items."}'::jsonb,
     true),
    ('purchase_request.responded', 'in_app',
     '{"ar": "تم الرد على طلب التسعير #{request_id}", "en": "RFQ Response Received #{request_id}"}'::jsonb,
     '{"ar": "قدم المورد {vendor_name} عرض أسعار لطلب التسعير الخاص بك.", "en": "Supplier {vendor_name} submitted a price quote for your RFQ."}'::jsonb,
     true),
    ('quote.requested', 'in_app',
     '{"ar": "طلب عرض سعر جديد", "en": "New Quote Requested"}'::jsonb,
     '{"ar": "طلبت صيدلية {customer_name} عرض سعر لمنتج {product_name} بكمية {quantity}.", "en": "Pharmacy {customer_name} requested a price quote for {product_name} (qty: {quantity})."}'::jsonb,
     true),
    ('quote.provided', 'in_app',
     '{"ar": "تم تقديم عرض سعر لمنتجك", "en": "Price Quote Provided"}'::jsonb,
     '{"ar": "قدم المورد {vendor_name} عرض سعر لمنتج {product_name} بسعر {quote_price} ج.م.", "en": "Supplier {vendor_name} provided a quote for {product_name} at {quote_price} EGP."}'::jsonb,
     true),
    ('quote.decision', 'in_app',
     '{"ar": "قرار بشأن عرض السعر", "en": "Quote Decision"}'::jsonb,
     '{"ar": "قام العميل {customer_name} بـ {decision} عرض السعر الخاص بمنتج {product_name}.", "en": "Customer {customer_name} has {decision} the quote for {product_name}."}'::jsonb,
     true),
    ('negotiation.offer', 'in_app',
     '{"ar": "عرض تفاوض سعر جديد", "en": "New Negotiation Offer"}'::jsonb,
     '{"ar": "اقترحت صيدلية {customer_name} سعراً تفاوضياً بقيمة {proposed_amount} ج.م للطلب {order_number}.", "en": "Pharmacy {customer_name} proposed {proposed_amount} EGP for order {order_number}."}'::jsonb,
     true),
    ('negotiation.decision', 'in_app',
     '{"ar": "قرار التفاوض على السعر", "en": "Negotiation Decision"}'::jsonb,
     '{"ar": "تم {decision} عرض التفاوض للطلب {order_number} من قبل المورد {vendor_name}. {reason}", "en": "Negotiation offer for order {order_number} was {decision} by {vendor_name}. {reason}"}'::jsonb,
     true),

    -- Promotions & Ads
    ('special_offer.status', 'in_app',
     '{"ar": "حالة العرض الخاص: {status}", "en": "Special Offer Status: {status}"}'::jsonb,
     '{"ar": "تم {status} العرض الخاص ''{offer_title}''. {reason}", "en": "Special offer ''{offer_title}'' has been {status}. {reason}"}'::jsonb,
     true),
    ('sponsorship.status', 'in_app',
     '{"ar": "حالة باقة الرعاية: {status}", "en": "Sponsorship Status: {status}"}'::jsonb,
     '{"ar": "تم {status} طلب باقة الرعاية ''{package_title}''. {reason}", "en": "Sponsorship package ''{package_title}'' has been {status}. {reason}"}'::jsonb,
     true),
    ('ad.status', 'in_app',
     '{"ar": "حالة الإعلان: {status}", "en": "Advertisement Status: {status}"}'::jsonb,
     '{"ar": "تم {status} إعلانك ''{ad_title}''. {reason}", "en": "Your ad ''{ad_title}'' has been {status}. {reason}"}'::jsonb,
     true),

    -- Smart Order & Imports
    ('smart_order.run_finished', 'in_app',
     '{"ar": "اكتملت جولة الطلب الذكي بنجاح", "en": "Smart Order Run Completed"}'::jsonb,
     '{"ar": "تمت معالجة جولة الطلب الذكي #{run_id} بنجاح. يمكنك الآن مراجعة المسودة وتأكيد الطلبات.", "en": "Smart order run #{run_id} completed successfully. You may now review and confirm orders."}'::jsonb,
     true),
    ('smart_order.run_failed', 'in_app',
     '{"ar": "تعذر إكمال جولة الطلب الذكي", "en": "Smart Order Run Failed"}'::jsonb,
     '{"ar": "فشلت معالجة جولة الطلب الذكي #{run_id}: {error}. يرجى المحاولة مرة أخرى.", "en": "Smart order run #{run_id} failed: {error}. Please try again."}'::jsonb,
     true),
    ('import.run_finished', 'in_app',
     '{"ar": "اكتمل استيراد المنتجات بنجاح", "en": "Catalog Import Completed"}'::jsonb,
     '{"ar": "تم إكمال ملف الاستيراد #{run_id} بنجاح بعد معالجة {rows_count} صفاً.", "en": "Import run #{run_id} completed successfully with {rows_count} rows processed."}'::jsonb,
     true),
    ('import.run_failed', 'in_app',
     '{"ar": "فشل استيراد المنتجات", "en": "Catalog Import Failed"}'::jsonb,
     '{"ar": "تعذر استكمال عملية الاستيراد #{run_id}: {error}.", "en": "Catalog import run #{run_id} could not be completed: {error}."}'::jsonb,
     true),

    -- Quotas
    ('quota.exhausted', 'in_app',
     '{"ar": "استنفاد الحصة التوريدية للفرع", "en": "Branch Quota Exhausted"}'::jsonb,
     '{"ar": "تم استنفاد حصة الفرع {branch_name} لدى المورد {vendor_name} للمنتج {product_name}.", "en": "Quota exhausted for branch {branch_name} with supplier {vendor_name} for {product_name}."}'::jsonb,
     true),
    ('quota.released', 'in_app',
     '{"ar": "إتاحة وتجديد الحصة التوريدية", "en": "Quota Released"}'::jsonb,
     '{"ar": "قام المورد {vendor_name} بإتاحة وتجديد الحصة للفرع {branch_name} للمنتج {product_name}.", "en": "Supplier {vendor_name} released quota for branch {branch_name} for product {product_name}."}'::jsonb,
     true),

    -- Profile & Organization Changes
    ('org.profile_change.requested', 'in_app',
     '{"ar": "طلب تعديل بيانات المنشأة {org_name}", "en": "Profile Change Requested: {org_name}"}'::jsonb,
     '{"ar": "قدمت المنشأة {org_name} طلباً لتعديل بيانات ملفها ({section}) بانتظار مراجعة الإدارة.", "en": "Organization {org_name} requested profile changes ({section}) awaiting admin review."}'::jsonb,
     true),
    ('org.profile_change.approved', 'in_app',
     '{"ar": "تمت الموافقة على تعديل بيانات المنشأة", "en": "Profile Change Approved"}'::jsonb,
     '{"ar": "وافقت إدارة المنصة على طلب تعديل بيانات المنشأة في قسم ({section}).", "en": "Platform admins approved your profile change request for section ({section})."}'::jsonb,
     true),
    ('org.profile_change.rejected', 'in_app',
     '{"ar": "تم رفض تعديل بيانات المنشأة", "en": "Profile Change Rejected"}'::jsonb,
     '{"ar": "تم رفض طلب تعديل بيانات المنشأة لقسم ({section}). السبب: {reason}", "en": "Profile change request for section ({section}) was rejected. Reason: {reason}"}'::jsonb,
     true),

    -- Organization Deletion
    ('org.deletion.requested', 'in_app',
     '{"ar": "طلب حذف منشأة: {org_name}", "en": "Organization Deletion Requested: {org_name}"}'::jsonb,
     '{"ar": "قدم مالك المنشأة {org_name} طلباً لحذف حساب المنشأة. السبب: {reason}", "en": "The owner of organization {org_name} requested organization deletion. Reason: {reason}"}'::jsonb,
     true),
    ('org.deletion.approved', 'in_app',
     '{"ar": "تمت الموافقة على حذف المنشأة", "en": "Organization Deletion Approved"}'::jsonb,
     '{"ar": "تمت الموافقة على حذف المنشأة {org_name} من قبل إدارة المنصة وجارٍ تنفيذ الإجراءات.", "en": "Organization {org_name} deletion has been approved by platform administration."}'::jsonb,
     true),
    ('org.deletion.rejected', 'in_app',
     '{"ar": "تم رفض طلب حذف المنشأة", "en": "Organization Deletion Rejected"}'::jsonb,
     '{"ar": "تم رفض طلب حذف المنشأة {org_name}. السبب: {reason}", "en": "Organization {org_name} deletion request was rejected. Reason: {reason}"}'::jsonb,
     true),

    -- Account Deletion
    ('account.deletion.requested', 'in_app',
     '{"ar": "طلب حذف حساب مستخدم: {user_name}", "en": "User Account Deletion Requested: {user_name}"}'::jsonb,
     '{"ar": "قدم المستخدم {user_name} ({user_email}) طلباً لحذف حسابه. السبب: {reason}", "en": "User {user_name} ({user_email}) requested account deletion. Reason: {reason}"}'::jsonb,
     true),
    ('account.deletion.approved', 'in_app',
     '{"ar": "تمت الموافقة على حذف حسابك", "en": "Account Deletion Approved"}'::jsonb,
     '{"ar": "تمت الموافقة على طلب حذف حسابك من قبل إدارة المنصة وسيتم إنهاء جلساتك.", "en": "Your account deletion request has been approved by platform administration."}'::jsonb,
     true),
    ('account.deletion.rejected', 'in_app',
     '{"ar": "تم رفض طلب حذف حسابك", "en": "Account Deletion Rejected"}'::jsonb,
     '{"ar": "تم رفض طلب حذف حسابك الشخصي. السبب: {reason}", "en": "Your account deletion request was rejected. Reason: {reason}"}'::jsonb,
     true),

    -- Organization Lifecycle
    ('org.approved', 'in_app',
     '{"ar": "تهانينا! تم اعتماد منشأتك", "en": "Congratulations! Organization Approved"}'::jsonb,
     '{"ar": "تم اعتماد المنشأة رسمياً وتفعيل وصولك الكامل لكافة مميزات منصة دواء24.", "en": "Your organization has been officially approved with full access to Dawa24 platform."}'::jsonb,
     true),
    ('org.rejected', 'in_app',
     '{"ar": "تم رفض طلب تسجيل المنشأة", "en": "Organization Registration Rejected"}'::jsonb,
     '{"ar": "تم رفض طلب تسجيل المنشأة من قبل إدارة المنصة. {reason}", "en": "Organization registration was rejected by platform administration. {reason}"}'::jsonb,
     true),
    ('org.suspended', 'in_app',
     '{"ar": "تم إيقاف المنشأة مؤقتاً", "en": "Organization Suspended"}'::jsonb,
     '{"ar": "تم إيقاف حساب منشأتك مؤقتاً من قبل إدارة المنصة. {reason}", "en": "Your organization account has been suspended by platform administration. {reason}"}'::jsonb,
     true),
    ('org.reactivated', 'in_app',
     '{"ar": "تمت إعادة تفعيل المنشأة", "en": "Organization Reactivated"}'::jsonb,
     '{"ar": "تمت إعادة تفعيل حساب المنشأة بنجاح ويمكنك استئناف الأنشطة والمعاملات.", "en": "Your organization account has been reactivated. You may resume normal activity."}'::jsonb,
     true),

    -- Documents
    ('document.requested', 'in_app',
     '{"ar": "طلب مستند رسمي من الإدارة", "en": "Document Requested by Admin"}'::jsonb,
     '{"ar": "طالبت إدارة المنصة تقديم مستند ({document_name}): {description}. الموعد النهائي: {deadline_days} يوماً.", "en": "Platform admins requested document ({document_name}): {description}. Deadline: {deadline_days} days."}'::jsonb,
     true),
    ('document.verified', 'in_app',
     '{"ar": "تم توثيق واعتماد المستند", "en": "Document Verified"}'::jsonb,
     '{"ar": "تم توثيق المستند ({document_name}) واعتماده بنجاح.", "en": "Document ({document_name}) has been successfully verified."}'::jsonb,
     true),
    ('document.rejected', 'in_app',
     '{"ar": "تم رفض المستند المقدم", "en": "Document Rejected"}'::jsonb,
     '{"ar": "تم رفض المستند ({document_name}). السبب: {reason}", "en": "Document ({document_name}) was rejected. Reason: {reason}"}'::jsonb,
     true),

    -- Branches & Institutional Works
    ('branch.created', 'in_app',
     '{"ar": "إضافة فرع جديد: {branch_name}", "en": "New Branch Added: {branch_name}"}'::jsonb,
     '{"ar": "تمت إضافة الفرع الجديد ''{branch_name}'' (كود: {branch_code}) بنجاح إلى منظومة منشأتك.", "en": "New branch ''{branch_name}'' (code: {branch_code}) was added to your organization."}'::jsonb,
     true),
    ('branch.disabled', 'in_app',
     '{"ar": "تعطيل فرع: {branch_name}", "en": "Branch Disabled: {branch_name}"}'::jsonb,
     '{"ar": "تم تعطيل الفرع ''{branch_name}'' مؤقتاً وإيقاف استقبال الطلبات عليه.", "en": "Branch ''{branch_name}'' has been temporarily disabled."}'::jsonb,
     true),
    ('branch.institutional_works.changed', 'in_app',
     '{"ar": "تحديث الأعمال المؤسسية للفرع {branch_name}", "en": "Institutional Works Updated for {branch_name}"}'::jsonb,
     '{"ar": "تم تحديث إعدادات الأعمال المؤسسية (التأمين والخدمات) للفرع ''{branch_name}''.", "en": "Institutional works settings (insurance and coverage) updated for branch ''{branch_name}''."}'::jsonb,
     true),

    -- Team & Identity
    ('org.user.added', 'in_app',
     '{"ar": "إضافة عضو جديد للمنشأة", "en": "New Member Added to Organization"}'::jsonb,
     '{"ar": "تمت إضافة {user_name} إلى منشأة {org_name} بدور: {role_name}.", "en": "User {user_name} was added to {org_name} with role: {role_name}."}'::jsonb,
     true),
    ('org.user.removed', 'in_app',
     '{"ar": "إزالة عضو من المنشأة", "en": "Member Removed from Organization"}'::jsonb,
     '{"ar": "تمت إزالة العضو {user_name} من منشأة {org_name}.", "en": "Member {user_name} was removed from organization {org_name}."}'::jsonb,
     true),
    ('user.role.changed', 'in_app',
     '{"ar": "تحديث الصلاحيات والدور الوظيفي", "en": "Role & Permissions Updated"}'::jsonb,
     '{"ar": "تم تحديث دورك الوظيفي في المنشأة إلى: {new_role}.", "en": "Your organization role has been updated to: {new_role}."}'::jsonb,
     true),
    ('user.password.set_by_admin', 'in_app',
     '{"ar": "تعيين كلمة مرور جديدة لحسابك", "en": "Password Set by Administrator"}'::jsonb,
     '{"ar": "قام مسؤول المنصة بتعيين كلمة مرور جديدة لحسابك وتم إنهاء جميع الجلسات النشطة.", "en": "A platform administrator set a new password for your account and terminated all active sessions."}'::jsonb,
     true),
    ('account.registered', 'in_app',
     '{"ar": "مرحباً بك في منصة دواء24", "en": "Welcome to Dawa24"}'::jsonb,
     '{"ar": "تم إنشاء حسابك بنجاح. نحن سعداء بانضمامك لمنظومة دواء24 الرقمية للرعاية الصيدلانية.", "en": "Your account was created successfully. Welcome to Dawa24 healthcare network."}'::jsonb,
     true),
    ('admin.new_registration', 'in_app',
     '{"ar": "تسجيل منشأة جديدة بانتظار المراجعة", "en": "New Organization Registered"}'::jsonb,
     '{"ar": "تم تسجيل حساب منشأة جديد: {org_name} ({account_type}) ويتطلب التحقق والمراجعة.", "en": "A new organization registered: {org_name} ({account_type}) awaiting verification."}'::jsonb,
     true),

    -- Subscriptions & Billing
    ('subscription.updated', 'in_app',
     '{"ar": "تأكيد الاشتراك في الباقة", "en": "Subscription Activated"}'::jsonb,
     '{"ar": "تم تفعيل باقة {plan_name} ({cycle}) بنجاح وخصم {cost} ج.م من المحفظة.", "en": "Subscription to {plan_name} ({cycle}) activated successfully with {cost} EGP deducted."}'::jsonb,
     true),
    ('subscription.expiring', 'in_app',
     '{"ar": "تنبيه: اقتراب انتهاء باقة الاشتراك", "en": "Subscription Expiring Soon"}'::jsonb,
     '{"ar": "سينتهي اشتراكك في باقة {plan_name} خلال {days_left} أيام. يرجى تجديد الاشتراك لتجنب توقف الميزات.", "en": "Your subscription for {plan_name} expires in {days_left} days. Please renew to keep full access."}'::jsonb,
     true),
    ('subscription.expired', 'in_app',
     '{"ar": "انتهت صلاحية باقة الاشتراك", "en": "Subscription Expired"}'::jsonb,
     '{"ar": "انتهت صلاحية باقة {plan_name}. يرجى إعادة الاشتراك للاستمرار في الاستفادة من كافة الخدمات.", "en": "Your subscription for {plan_name} has expired. Please renew to resume services."}'::jsonb,
     true),
    ('billing.refund.issued', 'in_app',
     '{"ar": "تم إصدار استرداد مالي (Refund)", "en": "Refund Issued"}'::jsonb,
     '{"ar": "تم إصدار واسترداد مبلغ {amount} ج.م إلى محفظتك للطلب #{order_number}. السبب: {reason}", "en": "A refund of {amount} EGP was credited to your wallet for order #{order_number}. Reason: {reason}"}'::jsonb,
     true),

    -- Wallet
    ('wallet.deposit.pending', 'in_app',
     '{"ar": "طلب إيداع رصيد قيد المراجعة", "en": "Deposit Request Pending"}'::jsonb,
     '{"ar": "تم استلام طلب شحن الرصيد بمبلغ {amount} ج.م وجارٍ مراجعته من قبل إدارة المالية.", "en": "Deposit request of {amount} EGP received and is under financial review."}'::jsonb,
     true),
    ('wallet.deposit.approved', 'in_app',
     '{"ar": "تم إيداع الرصيد بنجاح", "en": "Wallet Deposit Approved"}'::jsonb,
     '{"ar": "تمت إضافة مبلغ {amount} ج.م إلى محفظتك بنجاح.", "en": "An amount of {amount} EGP has been credited to your wallet."}'::jsonb,
     true),
    ('wallet.deposit.rejected', 'in_app',
     '{"ar": "تم رفض طلب إيداع الرصيد", "en": "Wallet Deposit Rejected"}'::jsonb,
     '{"ar": "تم رفض طلب إيداع الرصيد بمبلغ {amount} ج.م. {reason}", "en": "Wallet deposit of {amount} EGP was rejected. {reason}"}'::jsonb,
     true),
    ('wallet.withdrawal.pending', 'in_app',
     '{"ar": "طلب سحب رصيد قيد المعالجة", "en": "Withdrawal Request Pending"}'::jsonb,
     '{"ar": "تم استلام طلب سحب مبلغ {amount} ج.م وهو قيد المراجعة والتحويل البنكي.", "en": "Withdrawal request of {amount} EGP received and is pending bank transfer."}'::jsonb,
     true),
    ('wallet.withdrawal.approved', 'in_app',
     '{"ar": "تمت الموافقة على سحب الرصيد", "en": "Withdrawal Approved"}'::jsonb,
     '{"ar": "تم تحويل مبلغ {amount} ج.م إلى حسابك البنكي بنجاح.", "en": "An amount of {amount} EGP has been successfully transferred to your bank account."}'::jsonb,
     true),
    ('wallet.withdrawal.rejected', 'in_app',
     '{"ar": "تم رفض طلب سحب الرصيد", "en": "Withdrawal Rejected"}'::jsonb,
     '{"ar": "تم رفض طلب سحب الرصيد بمبلغ {amount} ج.م. {reason}", "en": "Withdrawal request of {amount} EGP was rejected. {reason}"}'::jsonb,
     true),

    -- Reviews, Chat, HR
    ('org.review.created', 'in_app',
     '{"ar": "تقييم ورأي جديد لمنشأتك", "en": "New Review for Your Organization"}'::jsonb,
     '{"ar": "حصلت منشأتك على تقييم جديد ({rating}/5 نجوم): ''{review_text}''.", "en": "Your organization received a new review ({rating}/5 stars): ''{review_text}''."}'::jsonb,
     true),
    ('chat.message.offline', 'in_app',
     '{"ar": "رسالة محادثة جديدة أثناء غيابك", "en": "New Offline Chat Message"}'::jsonb,
     '{"ar": "أرسل إليك {sender_name} رسالة جديدة: ''{message_snippet}''.", "en": "User {sender_name} sent you a message: ''{message_snippet}''."}'::jsonb,
     true),
    ('hr.job_application.received', 'in_app',
     '{"ar": "طلب توظيف جديد لوظيفة: {job_title}", "en": "New Job Application: {job_title}"}'::jsonb,
     '{"ar": "قدم المتقدم {applicant_name} ({applicant_phone}) طلباً لشغل وظيفة ''{job_title}''.", "en": "Applicant {applicant_name} ({applicant_phone}) applied for job ''{job_title}''."}'::jsonb,
     true)
ON CONFLICT (slug) DO UPDATE
SET title = EXCLUDED.title,
    body = EXCLUDED.body,
    updated_at = now();

COMMIT;
