package rbac

func pharmacyNav() []NavSection {
	return []NavSection{
		{
			Key: "orders", NameAr: "الطلبات والشحنات", NameEn: "Orders & Shipments",
			Items: []NavItem{
				{Key: "dashboard", Href: "/customer/dashboard", Icon: "home",
					NameAr: "لوحة التحكم", NameEn: "Dashboard",
					Perm: "pharmacy.dashboard.view"},
				{Key: "purchase-request", Aliases: []string{"purchase_request", "smart-order", "smart_order"},
					Href: "/customer/purchase-request", Icon: "cart",
					NameAr: "طلب الشراء", NameEn: "Purchase request",
					Perm: "pharmacy.purchase_request.view", Also: []string{"pharmacy.smart_order.view"}},
				{Key: "purchase_priority", Href: "/customer/purchase-priority", Icon: "trending-up",
					NameAr: "أولويات الشراء", NameEn: "Purchase priority",
					Perm: "pharmacy.priority.view"},
				{Key: "orders", Href: "/orders", Icon: "truck",
					NameAr: "الطلبات والشحنات", NameEn: "Orders",
					Perm: "pharmacy.order.view"},
				{Key: "wallet", Href: "/customer/wallet", Icon: "wallet",
					NameAr: "المحفظة والرصيد", NameEn: "Wallet",
					Perm: "pharmacy.wallet.view"},
				{Key: "favorites", Href: "/favorites", Icon: "heart",
					NameAr: "المنتجات المفضلة", NameEn: "Favourites",
					Perm: "pharmacy.favorite.view"},
			},
		},
		{
			Key: "market", NameAr: "العروض والسوق", NameEn: "Offers & Market",
			Items: []NavItem{
				{Key: "offers", Href: "/offers", Icon: "tag",
					NameAr: "العروض والخصومات", NameEn: "Offers",
					Perm: "pharmacy.offer.view"},
				{Key: "saving_products", Href: "/customer/saving-products", Icon: "package",
					NameAr: "منتجات التوفير", NameEn: "Saving products",
					Perm: "pharmacy.saving_product.view"},
				{Key: "decision_memory", Href: "/customer/decision-memory", Icon: "zap",
					NameAr: "ذاكرة قرارات المطابقة", NameEn: "Match decisions",
					Perm: "pharmacy.decision_memory.view"},
				{Key: "suppliers", Href: "/suppliers", Icon: "building",
					NameAr: "دليل الموردين", NameEn: "Suppliers",
					Perm: "pharmacy.supplier.view"},
				{Key: "followed", Href: "/suppliers/followed", Icon: "heart-filled",
					NameAr: "الموردون المتابَعون", NameEn: "Followed suppliers",
					Perm: "pharmacy.supplier.follow"},
			},
		},
		{
			Key: "company", NameAr: "المنشأة والفروع", NameEn: "Company & Branches",
			Items: []NavItem{
				{Key: "branches", Href: "/customer/branches", Icon: "map-pin",
					NameAr: "فروع الصيدلية", NameEn: "Branches",
					Perm: "pharmacy.branch.view"},
				{Key: "team", Aliases: []string{"employees"},
					Href: "/customer/team", Icon: "users",
					NameAr: "فريق العمل والموظفون", NameEn: "Team",
					Perm: "pharmacy.team.view"},
				{Key: "roles", Href: "/customer/roles", Icon: "shield",
					NameAr: "الأدوار والصلاحيات", NameEn: "Roles & permissions",
					Perm: "pharmacy.role.view"},
				{Key: "documents", Href: "/customer/documents", Icon: "file",
					NameAr: "المستندات والتراخيص", NameEn: "Documents",
					Perm: "pharmacy.document.view"},
				{Key: "user_organization", Href: "/customer/user-organization", Icon: "users",
					NameAr: "ربط المستخدمين بالمنشأة", NameEn: "User links",
					Perm: "pharmacy.user_org.view"},
				{Key: "subscription", Href: "/customer/subscription", Icon: "sparkles",
					NameAr: "الاشتراك والعضوية", NameEn: "Subscription",
					Perm: "pharmacy.subscription.view"},
				{Key: "jobs", Href: "/customer/jobs", Icon: "briefcase",
					NameAr: "الوظائف والتوظيف", NameEn: "Jobs",
					Perm: "pharmacy.job.view"},
			},
		},
		{
			Key: "account", NameAr: "الحساب والأمان", NameEn: "Account & Security",
			Items: []NavItem{
				{Key: "ai_logs", Href: "/customer/ai-logs", Icon: "sparkles",
					NameAr: "سجل استهلاك الذكاء الاصطناعي", NameEn: "AI usage log",
					Perm: "pharmacy.ai_log.view"},
				{Key: "sessions", Href: "/customer/sessions", Icon: "shield",
					NameAr: "الأجهزة والجلسات النشطة", NameEn: "Active sessions",
					Perm: "pharmacy.session.view"},
			},
		},
	}
}
