package rbac

func adminNav() []NavSection {
	return []NavSection{
		{
			Key: "overview", NameAr: "الرئيسية والمتابعة", NameEn: "Overview",
			Items: []NavItem{
				{Key: "dashboard", Href: "/admin/dashboard", Icon: "chart",
					NameAr: "لوحة المعلومات الرئيسية", NameEn: "Dashboard",
					Perm: "platform.dashboard.view"},
				{Key: "notifications", Href: "/admin/notifications", Icon: "bell",
					NameAr: "مركز الإشعارات والتنبيهات", NameEn: "Notifications",
					Perm: "notifications.center.view"},
			},
		},
		{
			Key: "organizations", NameAr: "المؤسسة والمشرفين", NameEn: "Organizations & Staff",
			Items: []NavItem{
				{Key: "organizations", Href: "/admin/organizations", Icon: "building",
					NameAr: "المنشآت والمؤسسات", NameEn: "Organizations",
					Perm: "org.organization.view"},
				{Key: "branches", Href: "/admin/branches", Icon: "map-pin",
					NameAr: "الفروع والمستودعات", NameEn: "Branches",
					Perm: "org.branch.view"},
				{Key: "users", Href: "/admin/users", Icon: "users",
					NameAr: "المستخدمون والحسابات", NameEn: "Users",
					Perm: "identity.user.view"},
				{Key: "roles", Href: "/admin/roles", Icon: "shield",
					NameAr: "الأدوار والصلاحيات", NameEn: "Roles & permissions",
					Perm: "identity.admin_role.view"},
				{Key: "approvals", Aliases: []string{"documents", "ask_for"},
					Href: "/admin/approvals", Icon: "shield",
					NameAr: "اعتماد المنشآت والوثائق", NameEn: "Approvals",
					Perm: "org.approval.view", Also: []string{"hr.document.view"}},
				{Key: "employee_activities", Href: "/admin/employee-activities", Icon: "clock",
					NameAr: "نشاط الموظفين", NameEn: "Employee activity",
					Perm: "identity.activity.view"},
				{Key: "chat_history", Href: "/admin/chat/history", Icon: "inbox",
					NameAr: "سجل المحادثات", NameEn: "Chat history",
					Perm: "platform.chat.view"},
			},
		},
		{
			Key: "settings", NameAr: "الإعدادات والمحتوى", NameEn: "Settings & Content",
			Items: []NavItem{
				{Key: "settings", Href: "/admin/settings", Icon: "settings",
					NameAr: "إعدادات النظام العامة", NameEn: "System settings",
					Perm: "platform.setting.view"},
				{Key: "institutional", Href: "/admin/institutional", Icon: "layers",
					NameAr: "الأنشطة والأعمال المؤسسية", NameEn: "Institutional activities",
					Perm: "org.institutional_work.view"},
				{Key: "cities", Href: "/admin/cities", Icon: "location",
					NameAr: "المحافظات والمدن", NameEn: "Governorates & cities",
					Perm: "platform.geo.view"},
				{Key: "content", Aliases: []string{"highlight_sections"},
					Href: "/admin/content", Icon: "file",
					NameAr: "محتوى الصفحات والأقسام", NameEn: "Page content",
					Perm: "platform.content.view"},
				{Key: "translations", Href: "/admin/translations", Icon: "globe",
					NameAr: "اللغات والترجمة", NameEn: "Languages & translation",
					Perm: "platform.translation.view"},
				{Key: "system_pages", Href: "/admin/system-pages", Icon: "layers",
					NameAr: "التحكم في صفحات النظام", NameEn: "System pages",
					Perm: "platform.page_control.view"},
			},
		},
		{
			Key: "catalog", NameAr: "المنتجات والمخزون", NameEn: "Catalog & Inventory",
			Items: []NavItem{
				{Key: "products", Href: "/admin/products", Icon: "package",
					NameAr: "كتالوج الأدوية المعتمدة", NameEn: "Drug catalog",
					Perm: "catalog.product.view"},
				{Key: "categories", Href: "/admin/categories", Icon: "folder",
					NameAr: "فئات المنتجات", NameEn: "Categories",
					Perm: "catalog.category.view"},
				{Key: "import", Href: "/admin/products/import", Icon: "upload",
					NameAr: "استيراد الكتالوج العام", NameEn: "Catalog import",
					Perm: "catalog.import.view"},
				{Key: "product_images_import", Href: "/admin/products/images/import", Icon: "image",
					NameAr: "استيراد صور المنتجات", NameEn: "Product image import",
					Perm: "catalog.image_import.view"},
				{Key: "brands", Href: "/admin/brands", Icon: "tag",
					NameAr: "الشركات المصنعة", NameEn: "Manufacturers",
					Perm: "catalog.brand.view"},
				{Key: "product_child", Href: "/admin/product-child", Icon: "layers",
					NameAr: "أصناف الموردين", NameEn: "Vendor items",
					Perm: "catalog.vendor_product.view"},
				{Key: "adv_products", Href: "/admin/adv-products", Icon: "sparkles",
					NameAr: "رعاية المنتجات", NameEn: "Product sponsorships",
					Perm: "promo.adv_product.view"},
				{Key: "saving_products", Href: "/admin/saving-products", Icon: "tag",
					NameAr: "منتجات التوفير", NameEn: "Saving products",
					Perm: "catalog.saving_product.view"},
				{Key: "match_decisions", Href: "/admin/match-decisions", Icon: "zap",
					NameAr: "ذاكرة قرارات المطابقة", NameEn: "Match decisions",
					Perm: "catalog.match_decision.view"},
				{Key: "warehouses", Href: "/admin/warehouses", Icon: "building",
					NameAr: "المخازن", NameEn: "Warehouses",
					Perm: "inventory.warehouse.view"},
				{Key: "temp_warehouses", Href: "/admin/user/temparte-warehouses", Icon: "folder-open",
					NameAr: "المستودعات المؤقتة", NameEn: "Temporary warehouses",
					Perm: "inventory.temp_warehouse.view"},
				{Key: "my_temp_warehouses", Href: "/admin/my/temparte-warehouses", Icon: "folder-open",
					NameAr: "مستودعاتي المرفوعة", NameEn: "My uploaded warehouses",
					Perm: "inventory.my_temp_warehouse.view"},
				{Key: "weekly_coverages", Href: "/admin/weekly-coverages", Icon: "truck",
					NameAr: "التغطية الأسبوعية", NameEn: "Weekly coverage",
					Perm: "workflow.coverage.view"},
			},
		},
		{
			Key: "commerce", NameAr: "المبيعات والمالية", NameEn: "Sales & Finance",
			Items: []NavItem{
				{Key: "orders", Aliases: []string{"offer_orders"},
					Href: "/admin/orders", Icon: "truck",
					NameAr: "طلبات الشراء وأوامر التوريد", NameEn: "Orders",
					Perm: "commerce.order.view"},
				{Key: "finance", Aliases: []string{"invoices", "payments", "wallets", "earnings_order", "earnings_offers"},
					Href: "/admin/finance", Icon: "wallet",
					NameAr: "الإدارة المالية والمحافظ", NameEn: "Finance & wallets",
					Perm: "billing.finance.view",
					Also: []string{"billing.invoice.view", "billing.payment.view", "billing.wallet.read"}},
				{Key: "plans", Aliases: []string{"subscriptions"},
					Href: "/admin/plans", Icon: "sparkles",
					NameAr: "باقات وخطط الاشتراك", NameEn: "Subscription plans",
					Perm: "billing.subscription_plan.view"},
			},
		},
		{
			Key: "promo", NameAr: "العروض والتسويق", NameEn: "Offers & Marketing",
			Items: []NavItem{
				{Key: "offers", Href: "/admin/offers", Icon: "tag",
					NameAr: "مراجعة عروض الموردين", NameEn: "Vendor offers",
					Perm: "promo.offer.view"},
				{Key: "offers_packages", Href: "/admin/offers-packages", Icon: "package",
					NameAr: "باقات الرعايات والعروض", NameEn: "Sponsorship & Offer Packages",
					Perm: "promo.offer_package.view"},
				{Key: "offer_locations", Href: "/admin/offers/locations", Icon: "location",
					NameAr: "مواقع تغطية العروض", NameEn: "Offer locations",
					Perm: "promo.offer_location.view"},
				{Key: "analytics", Href: "/admin/analytics", Icon: "bar-chart",
					NameAr: "التحليلات والإحصائيات", NameEn: "Analytics",
					Perm: "platform.analytics.view"},
			},
		},
		{
			Key: "tools", NameAr: "الأدوات والخدمات", NameEn: "Tools & Services",
			Items: []NavItem{
				{Key: "messages", Href: "/admin/messages", Icon: "message-square",
					NameAr: "رسائل واستفسارات التواصل", NameEn: "Contact messages",
					Perm: "platform.message.view"},
				{Key: "jobs", Href: "/admin/jobs", Icon: "briefcase",
					NameAr: "وظائف وشواغر القطاع", NameEn: "Job listings",
					Perm: "hr.job.view"},
			},
		},
		{
			Key: "trash", NameAr: "إدارة المحذوفات", NameEn: "Trash",
			Items: []NavItem{
				{Key: "trash", Href: "/admin/trash-list", Icon: "trash",
					NameAr: "سلة المحذوفات الشاملة", NameEn: "Trash",
					Perm: "platform.trash.view"},
			},
		},
		{
			Key: "developer", NameAr: "المطور والتشخيص", NameEn: "Developer & Diagnostics",
			Items: []NavItem{
				{Key: "developers", Href: "/admin/developers", Icon: "terminal",
					NameAr: "أدوات المطورين والـ AI", NameEn: "Developer tools",
					Perm: "platform.developer.sql"},
			},
		},
	}
}
